package fql.examples;

public class NistExample  extends Example {

	@Override
	public String getName() {
		return "NIST";
	}

	@Override
	public String getText() {
		return s;
	}
	
	String s= "schema A = {"
			+ "\n nodes"
			+ "\n  capability,"
			+ "\n  capabilitycategories,"
			+ "\n  capabilityequipment,"
			+ "\n  capabilityindustry,"
			+ "\n  capabilitymaterials,"
			+ "\n  capabilityprocesses,"
			+ "\n  capabilitytypesofmolds,"
			+ "\n  equipmenttype,"
			+ "\n  industry,"
			+ "\n  material,"
			+ "\n  moldtypes,"
			+ "\n  process,"
			+ "\n  productorservicecategory,"
			+ "\n  supplier,"
			+ "\n  suppliercapabilities,"
			+ "\n  unitcode;"
			+ "\n attributes"
			+ "\n  capability_Capability_Name: capability -> string,"
			+ "\n  capability_Max_Length: capability -> string,"
			+ "\n  capability_Production_Volume_Max: capability -> string,"
			+ "\n  capability_Production_Volume_Min: capability -> string,"
			+ "\n  capability_Tolerance: capability -> string,"
			+ "\n  equipmenttype_EquipmentType_Name: equipmenttype -> string,"
			+ "\n  industry_Industry_Name: industry -> string,"
			+ "\n  material_Material_Name: material -> string,"
			+ "\n  moldtypes_MoldTypes_Name: moldtypes -> string,"
			+ "\n  process_Process_Name: process -> string,"
			+ "\n  productorservicecategory_Category_Name: productorservicecategory -> string,"
			+ "\n  productorservicecategory_isLeaf: productorservicecategory -> string,"
			+ "\n  supplier_Note: supplier -> string,"
			+ "\n  supplier_Source: supplier -> string,"
			+ "\n  unitcode_Code: unitcode -> string,"
			+ "\n  unitcode_Description: unitcode -> string;"
			+ "\n arrows"
			+ "\n  capability_Max_Length_Unit: capability -> unitcode,"
			+ "\n  capability_Parent_id: capability -> capability,"
			+ "\n  capability_Production_Volume_Max_Unit: capability -> unitcode,"
			+ "\n  capability_Production_Volume_Min_Unit: capability -> unitcode,"
			+ "\n  capability_Tolerance_Unit: capability -> unitcode,"
			+ "\n  capabilitycategories_Capability_id: capabilitycategories -> capability,"
			+ "\n  capabilitycategories_ProductOrServiceCategory_id: capabilitycategories -> productorservicecategory,"
			+ "\n  capabilityequipment_Capability_id: capabilityequipment -> capability,"
			+ "\n  capabilityequipment_EquipmentType_id: capabilityequipment -> equipmenttype,"
			+ "\n  capabilityindustry_Capability_id: capabilityindustry -> capability,"
			+ "\n  capabilityindustry_Industry_id: capabilityindustry -> industry,"
			+ "\n  capabilitymaterials_Capability_id: capabilitymaterials -> capability,"
			+ "\n  capabilitymaterials_Material_id: capabilitymaterials -> material,"
			+ "\n  capabilityprocesses_Capability_id: capabilityprocesses -> capability,"
			+ "\n  capabilityprocesses_Process_id: capabilityprocesses -> process,"
			+ "\n  capabilitytypesofmolds_Capability_id: capabilitytypesofmolds -> capability,"
			+ "\n  capabilitytypesofmolds_MoldTypes_id: capabilitytypesofmolds -> moldtypes,"
			+ "\n  productorservicecategory_Parent_id: productorservicecategory -> productorservicecategory,"
			+ "\n  suppliercapabilities_Capability_id: suppliercapabilities -> capability,"
			+ "\n  suppliercapabilities_Supplier_id: suppliercapabilities -> supplier;"
			+ "\n equations"
			+ "\n  productorservicecategory.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id = productorservicecategory.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id,"
			+ "\n  capability.capability_Parent_id.capability_Parent_id.capability_Parent_id = capability.capability_Parent_id.capability_Parent_id.capability_Parent_id.capability_Parent_id;"
			+ "\n}"
			+ "\n"
			+ "\ninstance A_inst = {"
			+ "\n nodes"
			+ "\n  unitcode -> {1, 2, 3, 4, 0, 999}, "
			+ "\n  productorservicecategory -> {1, 2, 3, 4, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20}, "
			+ "\n  equipmenttype -> {2, 3, 1, 8, 7, 9, 4, 6, 5, 10}, "
			+ "\n  industry -> {1, 2, 6, 4, 7, 8, 9, 5, 10, 11, 12, 13, 3, 14, 15, 16, 17}, "
			+ "\n  material -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41}, "
			+ "\n  moldtypes -> {1, 7, 8, 2, 3, 4, 9, 5, 6}, "
			+ "\n  process -> {1, 2, 3, 4, 5, 6, 7}, "
			+ "\n  supplier -> {1, 2, 3, 4, 5, 6, 7, 8}, "
			+ "\n  capability -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}, "
			+ "\n  capabilitycategories -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}, "
			+ "\n  capabilityequipment -> {1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 16, 17}, "
			+ "\n  capabilityindustry -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}, "
			+ "\n  capabilitymaterials -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88}, "
			+ "\n  capabilityprocesses -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 18, 19, 20}, "
			+ "\n  capabilitytypesofmolds -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11}, "
			+ "\n  suppliercapabilities -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};"
			+ "\n attributes"
			+ "\n  unitcode_Code -> {(1, \"EA\"), (2, \"Thousands\"), (3, \"Inch\"), (4, \"mm\"), (0, \"NULL\"), (999, \"NULL - WTF\")}, "
			+ "\n  unitcode_Description -> {(1, \"Each part/piece count\"), (2, \"1000 parts/pieces count\"), (3, \"Length measure in inches\"), (4, \"Length measure in millimeters\"), (0, \"No unit\"), (999, \"Possible error\")}, "
			+ "\n  productorservicecategory_Category_Name -> {(1, \"Custom Manufacturing & Fabricating\"), (2, \"Machining\"), (3, \"General machining\"), (4, \"Complex & Difficult Machining\"), (6, \"Sinker EDM\"), (7, \"Ram EDM\"), (8, \"Machinery Tools & Supplies\"), (9, \"Dies & Molds\"), (10, \"Injection Molds\"), (12, \"CNC Machining\"), (13, \"EDM\"), (14, \"Wire EDM\"), (15, \"Small Hole EDM\"), (16, \"Micro Hole EDM\"), (17, \"High Speed Small Hole EDM\"), (18, \"Forging Dies\"), (19, \"Extrusion Dies\"), (20, \"Rotary Dies\")}, "
			+ "\n  productorservicecategory_isLeaf -> {(1, 0), (2, 0), (3, 0), (4, 0), (6, 1), (7, 1), (8, 0), (9, 0), (10, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 0)}, "
			+ "\n  equipmenttype_EquipmentType_Name -> {(2, \"CNC 3-axis Milling Machine\"), (3, \"CNC 4-axis Milling Machine\"), (1, \"EDM\"), (8, \"Engraving Machine\"), (7, \"Honing Machine\"), (9, \"Jig Grinder\"), (4, \"Lathe\"), (6, \"Sinker EDM\"), (5, \"Surface Grinder\"), (10, \"Verticle CNC Milling Machine\")}, "
			+ "\n  industry_Industry_Name -> {(1, \"Aerospace\"), (2, \"Automotive\"), (6, \"Building/Construction\"), (4, \"Commercial\"), (7, \"Communication\"), (8, \"Consumer Goods\"), (9, \"Electrical\"), (5, \"Electrical Connectors\"), (10, \"Electronic\"), (11, \"Food Processing\"), (12, \"Industrial\"), (13, \"Marine\"), (3, \"Medical\"), (14, \"Military/Government\"), (15, \"Music\"), (16, \"Optical\"), (17, \"Recreational Vehicle\")}, "
			+ "\n  material_Material_Name -> {(1, \"4140 Alloy Steels\"), (2, \"A-2 Tool Steel\"), (3, \"H-13 Tool Steel\"), (4, \"Aluminum\"), (5, \"Stainless Steel\"), (6, \"Titanium\"), (7, \"Tool Steel\"), (8, \"Brass\"), (9, \"Cobalt\"), (10, \"A-6 Tool Steel\"), (11, \"Chrome\"), (12, \"Columbium\"), (13, \"Stainless Steel 300 Series\"), (14, \"Titanium Alloy Ti 6AI-4V\"), (15, \"Titanium Alloy Ti 6AI-4V ELI\"), (16, \"Titanium Alloy CP2\"), (17, \"Titanium Alloy CP4\"), (18, \"Carbon Steel\"), (19, \"Plastics\"), (20, \"Ferrous\"), (21, \"Non-Ferrous\"), (22, \"Castings\"), (23, \"Forgings\"), (24, \"Extrusions\"), (25, \"Alloy Steel\"), (26, \"S7 Tool Steel\"), (27, \"M2 Tool Steel\"), (28, \"D2 Tool Steel\"), (29, \"4130 Tool Steel\"), (30, \"Tool Steel 4340\"), (31, \"300 Stainless Steel\"), (32, \"Stainless Steel 302\"), (33, \"304 Stainless Steel\"), (34, \"316 Stainless Steel\"), (35, \"15-4 Stainless Steel\"), (36, \"17-4 Stainless Steel\"), (37, \"Others\"), (38, \"CR/HR Steel\"), (39, \"Pre-hardened Steel\"), (40, \"Fully Hardened Tool Steel\"), (41, \"P-20\")}, "
			+ "\n  moldtypes_MoldTypes_Name -> {(1, \"Blow Molds (Extrusion or Injection/Blow)\"), (7, \"Collapsible Core\"), (8, \"Die Cast Molds\"), (2, \"Hot Runners\"), (3, \"Inserts Only\"), (4, \"Liquid Silicone Molds\"), (9, \"Multi-Cavity/Family Injection Molds\"), (5, \"Plastic Injection\"), (6, \"Transfer/Compression (Rubber or Silicone)\")}, "
			+ "\n  process_Process_Name -> {(1, \"Sinker EDM\"), (2, \"Wire EDM\"), (3, \"Small Hole EDM\"), (4, \"EDM Drilling\"), (5, \"Electrode Machining\"), (6, \"Plunger EDM\"), (7, \"Ram EDM\")}, "
			+ "\n  supplier_Source -> {(1, \"B&B\"), (2, \"Tecomet\"), (3, \"Astro\"), (4, \"Bobs Design\"), (5, \"Wiegel Tool\"), (6, \"Industrial Tools & Die\"), (7, \"Pro Mold\"), (8, \"Klann Plastics and Canyon Plastics\")}, "
			+ "\n  supplier_Note -> {(1, \"\"), (2, \"\"), (3, \"\"), (4, \"\"), (5, \"\"), (6, \"\"), (7, \"This supplier has another capability registered under the Injection Molds category, but it is more about molding rather than making the mold. So I excluded that. It also has a separate capability profile about mold design that I excluded.\"), (8, \"I used the types of molds values from the Canyon Plastics.\")}, "
			+ "\n  capability_Capability_Name -> {(1, \"CNC Machining\"), (2, \"CNC & Conventional Machining (turning & milling)\"), (3, \"Sinker EDM\"), (4, \"Wire EDM\"), (5, \"EDM\"), (6, \"Electrical Discharge Machining Services\"), (7, \"Wire Electrical Discharge Machining\"), (8, \"Custom  Molds for Plastic, Rubber, and Die Cast parts\"), (9, \"Prototype and Production Mold Design & Manufacturing\"), (10, \"Plastic Mold Making Services\"), (11, \"Mold Design and Build\")}, "
			+ "\n  capability_Production_Volume_Min -> {(1, \"NULL\"), (2, 1), (3, \"NULL\"), (4, \"NULL\"), (5, \"NULL\"), (6, 1), (7, 1), (8, \"NULL\"), (9, \"NULL\"), (10, \"NULL\"), (11, \"NULL\")}, "
			+ "\n  capability_Production_Volume_Max -> {(1, \"NULL\"), (2, 1), (3, \"NULL\"), (4, \"NULL\"), (5, \"NULL\"), (6, 1000), (7, 1000000), (8, \"NULL\"), (9, \"NULL\"), (10, \"NULL\"), (11, \"NULL\")}, "
			+ "\n  capability_Max_Length -> {(1, 40), (2, \"NULL\"), (3, \"47.25\"), (4, \"18.25\"), (5, \"NULL\"), (6, 20), (7, 20), (8, \"NULL\"), (9, \"NULL\"), (10, \"NULL\"), (11, \"NULL\")}, "
			+ "\n  capability_Tolerance -> {(1, \"NULL\"), (2, \"NULL\"), (3, \"0.001\"), (4, \"0.005\"), (5, \"NULL\"), (6, \"0.0025\"), (7, \"0.000001\"), (8, \"NULL\"), (9, \"NULL\"), (10, \"NULL\"), (11, \"NULL\")};"
			+ "\n arrows"
			+ "\n  productorservicecategory_Parent_id -> {(1, 1), (2, 1), (3, 2), (4, 3), (6, 13), (7, 13), (8, 8), (9, 8), (10, 9), (12, 2), (13, 2), (14, 13), (15, 13), (16, 13), (17, 13), (18, 9), (19, 9), (20, 9)}, "
			+ "\n  capability_Parent_id -> {(1, 1), (2, 2), (3, 5), (4, 5), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)}, "
			+ "\n  capability_Production_Volume_Min_Unit -> {(1, 0), (2, 1), (3, 0), (4, 0), (5, 0), (6, 1), (7, 1), (8, 0), (9, 0), (10, 0), (11, 0)}, "
			+ "\n  capability_Production_Volume_Max_Unit -> {(1, 0), (2, 2), (3, 0), (4, 0), (5, 0), (6, 1), (7, 1), (8, 0), (9, 0), (10, 0), (11, 0)}, "
			+ "\n  capability_Max_Length_Unit -> {(1, 999), (2, 0), (3, 3), (4, 3), (5, 0), (6, 3), (7, 3), (8, 0), (9, 0), (10, 0), (11, 0)}, "
			+ "\n  capability_Tolerance_Unit -> {(1, 0), (2, 0), (3, 3), (4, 3), (5, 0), (6, 4), (7, 3), (8, 0), (9, 0), (10, 0), (11, 0)}, "
			+ "\n  capabilitycategories_Capability_id -> {(1, 1), (2, 1), (3, 2), (4, 2), (5, 3), (6, 4), (7, 5), (8, 6), (9, 6), (10, 6), (11, 7), (12, 7), (13, 7), (14, 7), (15, 2), (16, 8), (17, 9), (18, 10), (19, 11)}, "
			+ "\n  capabilitycategories_ProductOrServiceCategory_id -> {(1, 6), (2, 12), (3, 6), (4, 12), (5, 6), (6, 14), (7, 13), (8, 6), (9, 7), (10, 13), (11, 6), (12, 7), (13, 15), (14, 14), (15, 14), (16, 10), (17, 10), (18, 10), (19, 10)}, "
			+ "\n  capabilityequipment_Capability_id -> {(1, 8), (2, 8), (3, 9), (4, 9), (5, 9), (7, 10), (8, 10), (9, 10), (10, 10), (11, 10), (12, 10), (13, 10), (16, 11), (17, 11)}, "
			+ "\n  capabilityequipment_EquipmentType_id -> {(1, 2), (2, 3), (3, 2), (4, 3), (5, 1), (7, 4), (8, 5), (9, 6), (10, 7), (11, 8), (12, 10), (13, 9), (16, 10), (17, 1)}, "
			+ "\n  capabilityindustry_Capability_id -> {(1, 8), (2, 8), (3, 8), (4, 8), (5, 8), (6, 9), (7, 9), (8, 9), (9, 9), (10, 9), (11, 11), (12, 11), (13, 11), (14, 11), (15, 11), (16, 11), (17, 11), (18, 11), (19, 11), (20, 11), (21, 11), (22, 11), (23, 11), (24, 11)}, "
			+ "\n  capabilityindustry_Industry_id -> {(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 1), (7, 2), (8, 3), (9, 5), (10, 4), (11, 1), (12, 6), (13, 7), (14, 8), (15, 9), (16, 10), (17, 11), (18, 12), (19, 13), (20, 3), (21, 14), (22, 15), (23, 16), (24, 17)}, "
			+ "\n  capabilitymaterials_Capability_id -> {(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 2), (10, 2), (11, 2), (12, 2), (13, 2), (14, 2), (15, 2), (16, 2), (17, 3), (18, 3), (19, 3), (20, 3), (21, 3), (22, 3), (23, 3), (24, 3), (25, 3), (26, 3), (27, 3), (28, 4), (29, 4), (30, 4), (31, 4), (32, 4), (33, 4), (34, 4), (35, 4), (36, 4), (37, 4), (38, 4), (40, 6), (41, 6), (42, 6), (43, 6), (44, 6), (45, 6), (46, 7), (47, 7), (48, 7), (49, 7), (50, 7), (51, 7), (52, 7), (53, 2), (55, 8), (56, 8), (57, 8), (58, 8), (59, 8), (60, 8), (61, 8), (62, 8), (63, 8), (64, 8), (65, 8), (66, 8), (67, 8), (68, 8), (69, 9), (70, 9), (71, 9), (72, 9), (73, 9), (74, 9), (75, 9), (76, 9), (77, 9), (78, 9), (79, 9), (80, 9), (81, 9), (82, 9), (83, 10), (85, 10), (86, 10), (87, 11), (88, 11)}, "
			+ "\n  capabilitymaterials_Material_id -> {(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 10), (9, 4), (10, 8), (11, 12), (12, 13), (13, 14), (14, 15), (15, 16), (16, 17), (17, 18), (18, 5), (19, 6), (20, 4), (21, 8), (22, 19), (23, 20), (24, 21), (25, 22), (26, 23), (27, 24), (28, 4), (29, 5), (30, 6), (31, 8), (32, 18), (33, 19), (34, 20), (35, 21), (36, 22), (37, 23), (38, 24), (40, 25), (41, 4), (42, 8), (43, 18), (44, 9), (45, 5), (46, 25), (47, 4), (48, 8), (49, 18), (50, 5), (51, 6), (52, 9), (53, 6), (55, 2), (56, 26), (57, 27), (58, 3), (59, 28), (60, 29), (61, 30), (62, 31), (63, 32), (64, 33), (65, 34), (66, 35), (67, 36), (68, 38), (69, 2), (70, 26), (71, 27), (72, 3), (73, 28), (74, 29), (75, 30), (76, 31), (77, 32), (78, 33), (79, 34), (80, 35), (81, 36), (82, 38), (83, 4), (85, 39), (86, 40), (87, 3), (88, 41)}, "
			+ "\n  capabilityprocesses_Capability_id -> {(1, 1), (2, 1), (3, 2), (4, 2), (5, 2), (6, 2), (7, 3), (8, 3), (9, 3), (10, 4), (11, 4), (12, 4), (13, 6), (14, 6), (15, 6), (16, 7), (18, 7), (19, 7), (20, 7)}, "
			+ "\n  capabilityprocesses_Process_id -> {(1, 1), (2, 2), (3, 2), (4, 1), (5, 6), (6, 7), (7, 1), (8, 2), (9, 3), (10, 1), (11, 2), (12, 3), (13, 1), (14, 2), (15, 3), (16, 2), (18, 4), (19, 5), (20, 1)}, "
			+ "\n  capabilitytypesofmolds_Capability_id -> {(1, 10), (2, 10), (3, 10), (4, 10), (5, 10), (6, 10), (7, 11), (8, 11), (9, 11), (10, 11), (11, 11)}, "
			+ "\n  capabilitytypesofmolds_MoldTypes_id -> {(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 1), (8, 7), (9, 8), (10, 2), (11, 9)}, "
			+ "\n  suppliercapabilities_Supplier_id -> {(1, 1), (2, 1), (3, 3), (4, 3), (5, 3), (6, 4), (7, 5), (8, 6), (9, 6), (10, 7), (11, 8)}, "
			+ "\n  suppliercapabilities_Capability_id -> {(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)};"
			+ "\n} : A"
			+ "\n"
			+ "\nschema B = {"
			+ "\n nodes"
			+ "\n  edmcapability,"
			+ "\n  edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailscapabilities,"
			+ "\n  edmmachiningservicedetailsmaterials,"
			+ "\n  edmmachiningservicedetailspartlengths,"
			+ "\n  edmmachiningservicedetailsservices,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings,"
			+ "\n  industry,"
			+ "\n  machineshopservicedetails,"
			+ "\n  machineshopservicedetailscapability,"
			+ "\n  machineshopservicedetailsmaterials,"
			+ "\n  machineshopservicedetailsservices,"
			+ "\n  machiningcapability,"
			+ "\n  machiningcapabilitybycategory,"
			+ "\n  material,"
			+ "\n  materialbyservicecategory,"
			+ "\n  moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsindustryserved,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype,"
			+ "\n  moldmakingservicedetailsservices,"
			+ "\n  moldorprocesstype,"
			+ "\n  partlengthvaluelist,"
			+ "\n  service,"
			+ "\n  servicebycategory,"
			+ "\n  servicedetails,"
			+ "\n  servicesandconsultantscategory,"
			+ "\n  supplier,"
			+ "\n  supplierservicedetails;"
			+ "\n attributes"
			+ "\n  edmcapability_EDMCapabilitiesName: edmcapability -> string,"
			+ "\n  edmmachiningservicedetails_DoMicroMachining: edmmachiningservicedetails -> string,"
			+ "\n  industry_IndustryName: industry -> string,"
			+ "\n  machineshopservicedetailscapability_isSpecialty: machineshopservicedetailscapability -> string,"
			+ "\n  machiningcapability_MachiningCapabilityName: machiningcapability -> string,"
			+ "\n  machiningcapabilitybycategory_isSpecialty: machiningcapabilitybycategory -> string,"
			+ "\n  material_MaterialName: material -> string,"
			+ "\n  moldorprocesstype_MoldOrProcessTypeName: moldorprocesstype -> string,"
			+ "\n  partlengthvaluelist_LengthValue: partlengthvaluelist -> string,"
			+ "\n  service_ServiceName: service -> string,"
			+ "\n  servicedetails_ServiceDetailsName: servicedetails -> string,"
			+ "\n  servicesandconsultantscategory_CateoryName: servicesandconsultantscategory -> string,"
			+ "\n  servicesandconsultantscategory_isLeaf: servicesandconsultantscategory -> string,"
			+ "\n  supplier_CompanyInfo: supplier -> string,"
			+ "\n  supplier_Source: supplier -> string;"
			+ "\n arrows"
			+ "\n  edmmachiningservicedetails_ServiceDetailsID: edmmachiningservicedetails -> servicedetails,"
			+ "\n  edmmachiningservicedetailscapabilities_EDMCapabilityID: edmmachiningservicedetailscapabilities -> edmcapability,"
			+ "\n  edmmachiningservicedetailscapabilities_EDMMachiningServiceDetailsID: edmmachiningservicedetailscapabilities -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsmaterials_EDMMachiningServiceDetailsID: edmmachiningservicedetailsmaterials -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsmaterials_MaterialID: edmmachiningservicedetailsmaterials -> material,"
			+ "\n  edmmachiningservicedetailspartlengths_EDMMachiningServiceDetailsID: edmmachiningservicedetailspartlengths -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailspartlengths_PartLengthValueListID: edmmachiningservicedetailspartlengths -> partlengthvaluelist,"
			+ "\n  edmmachiningservicedetailsservices_EDMMachiningServiceDetailsID: edmmachiningservicedetailsservices -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsservices_ServiceID: edmmachiningservicedetailsservices -> service,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings_EDMMachiningServiceDetailsID: edmmachiningservicedetailsspecialtymachinings -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings_MachiningCapabilityID: edmmachiningservicedetailsspecialtymachinings -> machiningcapability,"
			+ "\n  machineshopservicedetails_ServiceDetailsID: machineshopservicedetails -> servicedetails,"
			+ "\n  machineshopservicedetailscapability_MachineShopServiceDetailsID: machineshopservicedetailscapability -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailscapability_MachiningCapabilityID: machineshopservicedetailscapability -> machiningcapability,"
			+ "\n  machineshopservicedetailsmaterials_MachineShopServiceDetailsID: machineshopservicedetailsmaterials -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailsmaterials_MaterialID: machineshopservicedetailsmaterials -> material,"
			+ "\n  machineshopservicedetailsservices_MachineShopServiceDetailsID: machineshopservicedetailsservices -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailsservices_ServiceID: machineshopservicedetailsservices -> service,"
			+ "\n  machiningcapabilitybycategory_MachiningCapabilityID: machiningcapabilitybycategory -> machiningcapability,"
			+ "\n  machiningcapabilitybycategory_ServiceCategoryID: machiningcapabilitybycategory -> servicesandconsultantscategory,"
			+ "\n  materialbyservicecategory_MaterialID: materialbyservicecategory -> material,"
			+ "\n  materialbyservicecategory_ServiceCateogryID: materialbyservicecategory -> servicesandconsultantscategory,"
			+ "\n  moldmakingservicedetails_ServiceDetailsID: moldmakingservicedetails -> servicedetails,"
			+ "\n  moldmakingservicedetailsindustryserved_IndustryID: moldmakingservicedetailsindustryserved -> industry,"
			+ "\n  moldmakingservicedetailsindustryserved_MoldMakingServiceDetailID: moldmakingservicedetailsindustryserved -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingCapabilityID: moldmakingservicedetailsmoldorprocesstype -> moldorprocesstype,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingServiceDetailsID: moldmakingservicedetailsmoldorprocesstype -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsservices_MoldMakingServiceDetailsID: moldmakingservicedetailsservices -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsservices_ServiceID: moldmakingservicedetailsservices -> service,"
			+ "\n  servicebycategory_ServiceCategoryID: servicebycategory -> servicesandconsultantscategory,"
			+ "\n  servicebycategory_ServiceID: servicebycategory -> service,"
			+ "\n  servicedetails_Category: servicedetails -> servicesandconsultantscategory,"
			+ "\n  servicesandconsultantscategory_ParentID: servicesandconsultantscategory -> servicesandconsultantscategory,"
			+ "\n  supplierservicedetails_ServiceDetailsID: supplierservicedetails -> servicedetails,"
			+ "\n  supplierservicedetails_SupplierID: supplierservicedetails -> supplier;"
			+ "\n equations"
			+ "\n  servicesandconsultantscategory.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID = servicesandconsultantscategory.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID;"
			+ "\n}"
			+ "\n"
			+ "\ninstance B_inst = {"
			+ "\n nodes"
			+ "\n  material -> {1, 2, 4, 5, 6, 7, 8, 9, 10, 11}, "
			+ "\n  industry -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, "
			+ "\n  machiningcapability -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36}, "
			+ "\n  moldorprocesstype -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, "
			+ "\n  partlengthvaluelist -> {1, 2, 3, 4, 5}, "
			+ "\n  edmcapability -> {1, 2, 3}, "
			+ "\n  servicesandconsultantscategory -> {1, 2, 3, 5, 6}, "
			+ "\n  supplier -> {2, 3, 4, 5, 6}, "
			+ "\n  service -> {2, 3, 6, 7, 8, 10, 15, 16, 17, 18, 19, 20, 23, 24, 25}, "
			+ "\n  servicebycategory -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25}, "
			+ "\n  servicedetails -> {3, 4, 5, 6, 7, 8, 9, 10}, "
			+ "\n  supplierservicedetails -> {4, 5, 6, 7, 8, 9, 10}, "
			+ "\n  edmmachiningservicedetails -> {2, 3, 4}, "
			+ "\n  edmmachiningservicedetailscapabilities -> {3, 4, 5, 6, 7, 8, 9}, "
			+ "\n  edmmachiningservicedetailsmaterials -> {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26}, "
			+ "\n  edmmachiningservicedetailspartlengths -> {1, 2, 3, 4, 5, 6}, "
			+ "\n  edmmachiningservicedetailsservices -> {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}, "
			+ "\n  edmmachiningservicedetailsspecialtymachinings -> {1, 3, 4, 5}, "
			+ "\n  machineshopservicedetails -> {1, 2}, "
			+ "\n  machineshopservicedetailscapability -> {14, 24, 23, 22, 15, 25, 18, 19, 20, 27, 16, 21, 31, 32, 17, 30, 29, 26, 34, 33, 42, 40, 43, 35, 38, 36, 39, 41, 37}, "
			+ "\n  machineshopservicedetailsmaterials -> {3, 4, 5, 6, 7, 8, 9, 10, 11, 12}, "
			+ "\n  machineshopservicedetailsservices -> {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}, "
			+ "\n  machiningcapabilitybycategory -> {1, 4, 7, 10, 13, 16, 19, 22, 2, 5, 8, 11, 14, 17, 20, 23, 3, 6, 9, 12, 15, 18, 21, 24, 25, 28, 36, 31, 35, 34, 26, 29, 32, 27, 30, 33}, "
			+ "\n  materialbyservicecategory -> {1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}, "
			+ "\n  moldmakingservicedetails -> {1, 2, 3}, "
			+ "\n  moldmakingservicedetailsindustryserved -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19}, "
			+ "\n  moldmakingservicedetailsmoldorprocesstype -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}, "
			+ "\n  moldmakingservicedetailsservices -> {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17};"
			+ "\n attributes"
			+ "\n  material_MaterialName -> {(1, \"Aluminum\"), (2, \"Brass\"), (4, \"Stainless Steel\"), (5, \"Steel / Steel Alloys\"), (6, \"Titanium\"), (7, \"Hardened Metals\"), (8, \"Ultra-hard Materials\"), (9, \"Glass\"), (10, \"Glass Ceramics\"), (11, \"Ceramics\")}, "
			+ "\n  industry_IndustryName -> {(1, \"Aerospace\"), (2, \"Automotive\"), (3, \"Electrical/Electronics\"), (4, \"Food Processing\"), (5, \"Industrial\"), (6, \"Marine\"), (7, \"Medical\"), (8, \"Military\"), (9, \"Optical\"), (10, \"Pharmaceutical\"), (11, \"Semiconduction\"), (12, \"Other\")}, "
			+ "\n  machiningcapability_MachiningCapabilityName -> {(1, \"Drilling\"), (2, \"Screw Machining\"), (3, \"Water/Abrasive Jet Machining\"), (4, \"Deep Hole Drilling\"), (5, \"Double-disc Grinding\"), (6, \"Jig Grinding\"), (7, \"Laser Machining\"), (8, \"Etching/Chemical Milling\"), (9, \"Milling\"), (10, \"Swiss Machining\"), (11, \"Jig Boring\"), (12, \"Centerless Grinding\"), (13, \"id/Internal Grinding\"), (14, \"Surface Grinding\"), (15, \"Electrode EDM\"), (16, \"Electrochemical/Photochemical Machining\"), (17, \"Turning\"), (18, \"Abrasive Flow Machining\"), (19, \"Broaching\"), (20, \"Creep Feed Grinding\"), (21, \"OD/External Grinding\"), (22, \"Honing\"), (24, \"Wire EDM\"), (25, \"Other\"), (26, \"Casting Machining\"), (27, \"Extrusion Machining\"), (28, \"Jigs and Fixtures\"), (29, \"Tool & Die Manufacturing\"), (30, \"CNC Machining\"), (31, \"Gear Manufacturing\"), (32, \"Thread Grinding\"), (33, \"Forging Machining\"), (34, \"Micro Machining\"), (35, \"Thread Rolling\"), (36, \"Jigs and Fixtures\")}, "
			+ "\n  moldorprocesstype_MoldOrProcessTypeName -> {(1, \"Blow Molding\"), (2, \"Compression Molding\"), (3, \"Die Casting\"), (4, \"Injection Molding\"), (5, \"Investment Casting\"), (6, \"Permanent Mold Casting\"), (7, \"Powder Metal Molding\"), (8, \"Rotational Molding\"), (9, \"Sand Casting\"), (10, \"Thermoforming\"), (11, \"Transfer Molding\"), (12, \"Other\")}, "
			+ "\n  partlengthvaluelist_LengthValue -> {(1, \"less than 1in\"), (2, \"1in - 3in\"), (3, \"3in - 6in\"), (4, \"6in - 48in\"), (5, \"Greater than 48in\")}, "
			+ "\n  edmcapability_EDMCapabilitiesName -> {(1, \"Electrode EDM\"), (2, \"Wire EDM\"), (3, \"Small Hole EDM\")}, "
			+ "\n  servicesandconsultantscategory_CateoryName -> {(1, \"Contract Manufacturing And Fabrication\"), (2, \"Part Fabrication Services\"), (3, \"Mold Making Services\"), (5, \"EDM Machining Services\"), (6, \"Machine Shop Services\")}, "
			+ "\n  servicesandconsultantscategory_isLeaf -> {(1, 0), (2, 0), (3, 1), (5, 1), (6, 1)}, "
			+ "\n  supplier_Source -> {(2, \"Apex\"), (3, \"Maudlin & Son\"), (4, \"Peridot\"), (5, \"3-D Service\"), (6, \"Control Plastics\")}, "
			+ "\n  supplier_CompanyInfo -> {(2, \"has great experiences.\"), (3, \"can do many kinds of works.\"), (4, \"will simplify your supply chain.\"), (5, \"specializes in making mold for the auto industry.\"), (6, \"is your sourcing destination.\")}, "
			+ "\n  service_ServiceName -> {(2, \"Design Assistance\"), (3, \"Just-in-Time Delivery\"), (6, \"High Volume Production\"), (7, \"Prototype Services\"), (8, \"Reverse Engineering\"), (10, \"CAD/CAM Support\"), (15, \"Model Making\"), (16, \"Production Facilities\"), (17, \"Prototyping\"), (18, \"Repair / Maintenance\"), (19, \"Low Volume Production\"), (20, \"Mold Texturing\"), (23, \"Other\"), (24, \"Assembly Services\"), (25, \"Field Machining\")}, "
			+ "\n  servicedetails_ServiceDetailsName -> {(3, \"Supplier_2 EDM Machining Service\"), (4, \"Supplier_3 EDM Machining Service\"), (5, \"Supplier_4 Machine Shop Service\"), (6, \"Supplier_4 EDM Machining Service\"), (7, \"Supplier_2 Mold Making Service\"), (8, \"Supplier_5 Mold Making Service\"), (9, \"Supplier_6 Mold Making Service\"), (10, \"Supplier_5 Maching Shop Service\")}, "
			+ "\n  edmmachiningservicedetails_DoMicroMachining -> {(2, 1), (3, 0), (4, 1)}, "
			+ "\n  machineshopservicedetailscapability_isSpecialty -> {(14, 0), (24, 0), (23, 0), (22, 0), (15, 0), (25, 0), (18, 0), (19, 0), (20, 0), (27, 0), (16, 0), (21, 0), (31, 1), (32, 1), (17, 0), (30, 1), (29, 1), (26, 0), (34, 0), (33, 0), (42, 0), (40, 0), (43, 0), (35, 0), (38, 0), (36, 0), (39, 0), (41, 0), (37, 0)}, "
			+ "\n  machiningcapabilitybycategory_isSpecialty -> {(1, 0), (4, 0), (7, 0), (10, 0), (13, 0), (16, 0), (19, 0), (22, 0), (2, 0), (5, 0), (8, 0), (11, 0), (14, 0), (17, 0), (20, 0), (23, 0), (3, 0), (6, 0), (9, 0), (12, 0), (15, 0), (18, 0), (21, 0), (24, 0), (25, 1), (28, 1), (36, 1), (31, 1), (35, 1), (34, 1), (26, 1), (29, 1), (32, 1), (27, 1), (30, 1), (33, 1)};"
			+ "\n arrows"
			+ "\n  servicesandconsultantscategory_ParentID -> {(1, 1), (2, 1), (3, 2), (5, 6), (6, 1)}, "
			+ "\n  servicebycategory_ServiceID -> {(1, 2), (2, 3), (3, 19), (4, 6), (5, 10), (6, 8), (7, 7), (8, 23), (9, 2), (10, 10), (11, 20), (12, 18), (13, 17), (14, 16), (15, 15), (16, 24), (17, 3), (18, 6), (19, 23), (20, 25), (21, 7), (22, 10), (23, 2), (24, 19), (25, 8)}, "
			+ "\n  servicebycategory_ServiceCategoryID -> {(1, 5), (2, 5), (3, 5), (4, 5), (5, 5), (6, 5), (7, 5), (8, 5), (9, 3), (10, 3), (11, 3), (12, 3), (13, 3), (14, 3), (15, 3), (16, 6), (17, 6), (18, 6), (19, 6), (20, 6), (21, 6), (22, 6), (23, 6), (24, 6), (25, 6)}, "
			+ "\n  servicedetails_Category -> {(3, 5), (4, 5), (5, 6), (6, 5), (7, 3), (8, 3), (9, 3), (10, 6)}, "
			+ "\n  supplierservicedetails_SupplierID -> {(4, 2), (5, 3), (6, 4), (7, 4), (8, 2), (9, 5), (10, 6)}, "
			+ "\n  supplierservicedetails_ServiceDetailsID -> {(4, 3), (5, 4), (6, 5), (7, 6), (8, 7), (9, 8), (10, 9)}, "
			+ "\n  edmmachiningservicedetails_ServiceDetailsID -> {(2, 3), (3, 4), (4, 6)}, "
			+ "\n  edmmachiningservicedetailscapabilities_EDMMachiningServiceDetailsID -> {(3, 2), (4, 3), (5, 2), (6, 2), (7, 4), (8, 4), (9, 4)}, "
			+ "\n  edmmachiningservicedetailscapabilities_EDMCapabilityID -> {(3, 1), (4, 2), (5, 3), (6, 2), (7, 1), (8, 2), (9, 3)}, "
			+ "\n  edmmachiningservicedetailsmaterials_EDMMachiningServiceDetailsID -> {(7, 2), (8, 2), (9, 2), (10, 2), (11, 2), (12, 2), (13, 3), (14, 3), (15, 3), (16, 3), (17, 3), (18, 3), (19, 3), (20, 4), (21, 4), (22, 4), (23, 4), (24, 4), (25, 4), (26, 2)}, "
			+ "\n  edmmachiningservicedetailsmaterials_MaterialID -> {(7, 2), (8, 7), (9, 4), (10, 5), (11, 6), (12, 8), (13, 1), (14, 2), (15, 7), (16, 4), (17, 5), (18, 6), (19, 8), (20, 1), (21, 7), (22, 4), (23, 5), (24, 6), (25, 8), (26, 1)}, "
			+ "\n  edmmachiningservicedetailspartlengths_EDMMachiningServiceDetailsID -> {(1, 4), (2, 4), (3, 4), (4, 2), (5, 3), (6, 2)}, "
			+ "\n  edmmachiningservicedetailspartlengths_PartLengthValueListID -> {(1, 1), (2, 2), (3, 3), (4, 1), (5, 4), (6, 5)}, "
			+ "\n  edmmachiningservicedetailsservices_EDMMachiningServiceDetailsID -> {(7, 2), (8, 2), (9, 2), (10, 2), (11, 2), (12, 3), (13, 3), (14, 3), (15, 3), (16, 3), (17, 4), (18, 4), (19, 4), (20, 4), (21, 4), (22, 4), (23, 2), (24, 2)}, "
			+ "\n  edmmachiningservicedetailsservices_ServiceID -> {(7, 2), (8, 3), (9, 7), (10, 19), (11, 6), (12, 10), (13, 3), (14, 19), (15, 6), (16, 8), (17, 10), (18, 2), (19, 7), (20, 19), (21, 6), (22, 8), (23, 10), (24, 8)}, "
			+ "\n  edmmachiningservicedetailsspecialtymachinings_EDMMachiningServiceDetailsID -> {(1, 4), (3, 2), (4, 2), (5, 3)}, "
			+ "\n  edmmachiningservicedetailsspecialtymachinings_MachiningCapabilityID -> {(1, 29), (3, 29), (4, 28), (5, 28)}, "
			+ "\n  machineshopservicedetails_ServiceDetailsID -> {(1, 5), (2, 10)}, "
			+ "\n  machineshopservicedetailscapability_MachineShopServiceDetailsID -> {(14, 1), (24, 1), (23, 1), (22, 1), (15, 1), (25, 1), (18, 1), (19, 1), (20, 1), (27, 1), (16, 1), (21, 1), (31, 1), (32, 1), (17, 1), (30, 1), (29, 1), (26, 1), (34, 2), (33, 2), (42, 2), (40, 2), (43, 2), (35, 2), (38, 2), (36, 2), (39, 2), (41, 2), (37, 2)}, "
			+ "\n  machineshopservicedetailscapability_MachiningCapabilityID -> {(14, 1), (24, 2), (23, 7), (22, 8), (15, 9), (25, 10), (18, 12), (19, 14), (20, 15), (27, 16), (16, 17), (21, 24), (31, 28), (32, 29), (17, 30), (30, 31), (29, 34), (26, 35), (34, 1), (33, 3), (42, 4), (40, 6), (43, 7), (35, 9), (38, 13), (36, 17), (39, 21), (41, 24), (37, 30)}, "
			+ "\n  machineshopservicedetailsmaterials_MachineShopServiceDetailsID -> {(3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 2), (11, 2), (12, 2)}, "
			+ "\n  machineshopservicedetailsmaterials_MaterialID -> {(3, 1), (4, 2), (5, 7), (6, 4), (7, 5), (8, 6), (9, 8), (10, 1), (11, 4), (12, 5)}, "
			+ "\n  machineshopservicedetailsservices_MachineShopServiceDetailsID -> {(2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 2), (12, 2), (13, 2), (14, 2), (15, 2)}, "
			+ "\n  machineshopservicedetailsservices_ServiceID -> {(2, 24), (3, 25), (4, 10), (5, 2), (6, 3), (7, 7), (8, 19), (9, 6), (10, 8), (11, 24), (12, 10), (13, 2), (14, 7), (15, 19)}, "
			+ "\n  machiningcapabilitybycategory_MachiningCapabilityID -> {(1, 1), (4, 2), (7, 3), (10, 4), (13, 5), (16, 6), (19, 7), (22, 8), (2, 9), (5, 10), (8, 11), (11, 12), (14, 13), (17, 14), (20, 15), (23, 16), (3, 17), (6, 18), (9, 19), (12, 20), (15, 21), (18, 22), (21, 24), (24, 25), (25, 26), (28, 27), (36, 28), (31, 28), (35, 29), (34, 29), (26, 30), (29, 31), (32, 32), (27, 33), (30, 34), (33, 35)}, "
			+ "\n  machiningcapabilitybycategory_ServiceCategoryID -> {(1, 6), (4, 6), (7, 6), (10, 6), (13, 6), (16, 6), (19, 6), (22, 6), (2, 6), (5, 6), (8, 6), (11, 6), (14, 6), (17, 6), (20, 6), (23, 6), (3, 6), (6, 6), (9, 6), (12, 6), (15, 6), (18, 6), (21, 6), (24, 6), (25, 6), (28, 6), (36, 5), (31, 6), (35, 5), (34, 6), (26, 6), (29, 6), (32, 6), (27, 6), (30, 6), (33, 6)}, "
			+ "\n  materialbyservicecategory_MaterialID -> {(1, 1), (2, 2), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (9, 1), (10, 2), (11, 4), (12, 5), (13, 6), (14, 7), (15, 8), (16, 9), (17, 11), (18, 10)}, "
			+ "\n  materialbyservicecategory_ServiceCateogryID -> {(1, 5), (2, 5), (3, 5), (4, 5), (5, 5), (6, 5), (7, 5), (9, 6), (10, 6), (11, 6), (12, 6), (13, 6), (14, 6), (15, 6), (16, 6), (17, 6), (18, 6)}, "
			+ "\n  moldmakingservicedetails_ServiceDetailsID -> {(1, 7), (2, 8), (3, 9)}, "
			+ "\n  moldmakingservicedetailsindustryserved_MoldMakingServiceDetailID -> {(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 2), (10, 3), (11, 3), (12, 3), (13, 3), (14, 3), (15, 3), (16, 3), (17, 3), (18, 3), (19, 3)}, "
			+ "\n  moldmakingservicedetailsindustryserved_IndustryID -> {(1, 1), (2, 3), (3, 5), (4, 6), (5, 7), (6, 8), (7, 9), (8, 11), (9, 2), (10, 1), (11, 3), (12, 4), (13, 5), (14, 6), (15, 7), (16, 8), (17, 9), (18, 10), (19, 11)}, "
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingServiceDetailsID -> {(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2), (8, 3), (9, 3), (10, 3), (11, 3), (12, 3), (13, 3), (14, 3), (15, 3)}, "
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingCapabilityID -> {(1, 2), (2, 6), (3, 7), (4, 9), (5, 10), (6, 11), (7, 4), (8, 2), (9, 3), (10, 4), (11, 5), (12, 6), (13, 7), (14, 9), (15, 10)}, "
			+ "\n  moldmakingservicedetailsservices_MoldMakingServiceDetailsID -> {(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 2), (9, 2), (10, 2), (11, 2), (12, 2), (13, 2), (14, 3), (15, 3), (16, 3), (17, 3)}, "
			+ "\n  moldmakingservicedetailsservices_ServiceID -> {(1, 15), (2, 20), (3, 16), (4, 17), (5, 18), (6, 10), (7, 2), (8, 15), (9, 16), (10, 17), (11, 18), (12, 10), (13, 2), (14, 20), (15, 16), (16, 10), (17, 2)};"
			+ "\n} : B"
			+ "\n"
			+ "\n"
			+ "\nschema C = {"
			+ "\n nodes"
			+ "\n  capability,"
			+ "\n  capabilitycategories,"
			+ "\n  capabilityequipment,"
			+ "\n  capabilityindustry,"
			+ "\n  capabilitymaterials,"
			+ "\n  capabilityprocesses,"
			+ "\n  capabilitytypesofmolds,"
			+ "\n  equipmenttype,"
			+ "\n  material_A,"
			+ "\n  moldtypes,"
			+ "\n  process,"
			+ "\n  suppliercapabilities,"
			+ "\n  unitcode,"
			+ "\n //"
			+ "\n  edmcapability,"
			+ "\n  edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailscapabilities,"
			+ "\n  edmmachiningservicedetailsmaterials,"
			+ "\n  edmmachiningservicedetailspartlengths,"
			+ "\n  edmmachiningservicedetailsservices,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings,"
			+ "\n  industry,"
			+ "\n  machineshopservicedetails,"
			+ "\n  machineshopservicedetailscapability,"
			+ "\n  machineshopservicedetailsmaterials,"
			+ "\n  machineshopservicedetailsservices,"
			+ "\n  machiningcapability,"
			+ "\n  machiningcapabilitybycategory,"
			+ "\n  material_B,"
			+ "\n  materialbyservicecategory,"
			+ "\n  moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsindustryserved,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype,"
			+ "\n  moldmakingservicedetailsservices,"
			+ "\n  moldorprocesstype,"
			+ "\n  partlengthvaluelist,"
			+ "\n  service,"
			+ "\n  servicebycategory,"
			+ "\n  servicedetails,"
			+ "\n  servicesandconsultantscategory,"
			+ "\n  supplier,"
			+ "\n  supplierservicedetails,"
			+ "\n//many-to-many"
			+ "\n capability_service,"
			+ "\n material_material;"
			+ "\n attributes"
			+ "\n  capability_Capability_Name: capability -> string,"
			+ "\n  capability_Max_Length: capability -> string,"
			+ "\n  capability_Production_Volume_Max: capability -> string,"
			+ "\n  capability_Production_Volume_Min: capability -> string,"
			+ "\n  capability_Tolerance: capability -> string,"
			+ "\n  equipmenttype_EquipmentType_Name: equipmenttype -> string,"
			+ "\n  industry_Industry_Name: industry -> string,"
			+ "\n  material_Material_Name: material_A -> string,"
			+ "\n  moldtypes_MoldTypes_Name: moldtypes -> string,"
			+ "\n  process_Process_Name: process -> string,"
			+ "\n  productorservicecategory_Category_Name: servicesandconsultantscategory -> string,"
			+ "\n  productorservicecategory_isLeaf: servicesandconsultantscategory -> string,"
			+ "\n  supplier_Note: supplier -> string,"
			+ "\n  unitcode_Code: unitcode -> string,"
			+ "\n  unitcode_Description: unitcode -> string,"
			+ "\n//"
			+ "\nedmcapability_EDMCapabilitiesName: edmcapability -> string,"
			+ "\n  edmmachiningservicedetails_DoMicroMachining: edmmachiningservicedetails -> string,"
			+ "\n  industry_IndustryName: industry -> string,"
			+ "\n  machineshopservicedetailscapability_isSpecialty: machineshopservicedetailscapability -> string,"
			+ "\n  machiningcapability_MachiningCapabilityName: machiningcapability -> string,"
			+ "\n  machiningcapabilitybycategory_isSpecialty: machiningcapabilitybycategory -> string,"
			+ "\n  material_MaterialName: material_B -> string,"
			+ "\n  moldorprocesstype_MoldOrProcessTypeName: moldorprocesstype -> string,"
			+ "\n  partlengthvaluelist_LengthValue: partlengthvaluelist -> string,"
			+ "\n  service_ServiceName: service -> string,"
			+ "\n  servicedetails_ServiceDetailsName: servicedetails -> string,"
			+ "\n  servicesandconsultantscategory_CateoryName: servicesandconsultantscategory -> string,"
			+ "\n  servicesandconsultantscategory_isLeaf: servicesandconsultantscategory -> string,"
			+ "\n  supplier_CompanyInfo: supplier -> string,"
			+ "\n  supplier_Source: supplier -> string;  "
			+ "\n arrows"
			+ "\n  capability_Max_Length_Unit: capability -> unitcode,"
			+ "\n  capability_Parent_id: capability -> capability,"
			+ "\n  capability_Production_Volume_Max_Unit: capability -> unitcode,"
			+ "\n  capability_Production_Volume_Min_Unit: capability -> unitcode,"
			+ "\n  capability_Tolerance_Unit: capability -> unitcode,"
			+ "\n  capabilitycategories_Capability_id: capabilitycategories -> capability,"
			+ "\n  capabilitycategories_ProductOrServiceCategory_id: capabilitycategories -> servicesandconsultantscategory,"
			+ "\n  capabilityequipment_Capability_id: capabilityequipment -> capability,"
			+ "\n  capabilityequipment_EquipmentType_id: capabilityequipment -> equipmenttype,"
			+ "\n  capabilityindustry_Capability_id: capabilityindustry -> capability,"
			+ "\n  capabilityindustry_Industry_id: capabilityindustry -> industry,"
			+ "\n  capabilitymaterials_Capability_id: capabilitymaterials -> capability,"
			+ "\n  capabilitymaterials_Material_id: capabilitymaterials -> material_A,"
			+ "\n  capabilityprocesses_Capability_id: capabilityprocesses -> capability,"
			+ "\n  capabilityprocesses_Process_id: capabilityprocesses -> process,"
			+ "\n  capabilitytypesofmolds_Capability_id: capabilitytypesofmolds -> capability,"
			+ "\n  capabilitytypesofmolds_MoldTypes_id: capabilitytypesofmolds -> moldtypes,"
			+ "\n  suppliercapabilities_Capability_id: suppliercapabilities -> capability,"
			+ "\n  suppliercapabilities_Supplier_id: suppliercapabilities -> supplier,"
			+ "\n//"
			+ "\nedmmachiningservicedetails_ServiceDetailsID: edmmachiningservicedetails -> servicedetails,"
			+ "\n  edmmachiningservicedetailscapabilities_EDMCapabilityID: edmmachiningservicedetailscapabilities -> edmcapability,"
			+ "\n  edmmachiningservicedetailscapabilities_EDMMachiningServiceDetailsID: edmmachiningservicedetailscapabilities -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsmaterials_EDMMachiningServiceDetailsID: edmmachiningservicedetailsmaterials -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsmaterials_MaterialID: edmmachiningservicedetailsmaterials -> material_B,"
			+ "\n  edmmachiningservicedetailspartlengths_EDMMachiningServiceDetailsID: edmmachiningservicedetailspartlengths -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailspartlengths_PartLengthValueListID: edmmachiningservicedetailspartlengths -> partlengthvaluelist,"
			+ "\n  edmmachiningservicedetailsservices_EDMMachiningServiceDetailsID: edmmachiningservicedetailsservices -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsservices_ServiceID: edmmachiningservicedetailsservices -> service,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings_EDMMachiningServiceDetailsID: edmmachiningservicedetailsspecialtymachinings -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings_MachiningCapabilityID: edmmachiningservicedetailsspecialtymachinings -> machiningcapability,"
			+ "\n  machineshopservicedetails_ServiceDetailsID: machineshopservicedetails -> servicedetails,"
			+ "\n  machineshopservicedetailscapability_MachineShopServiceDetailsID: machineshopservicedetailscapability -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailscapability_MachiningCapabilityID: machineshopservicedetailscapability -> machiningcapability,"
			+ "\n  machineshopservicedetailsmaterials_MachineShopServiceDetailsID: machineshopservicedetailsmaterials -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailsmaterials_MaterialID: machineshopservicedetailsmaterials -> material_B,"
			+ "\n  machineshopservicedetailsservices_MachineShopServiceDetailsID: machineshopservicedetailsservices -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailsservices_ServiceID: machineshopservicedetailsservices -> service,"
			+ "\n  machiningcapabilitybycategory_MachiningCapabilityID: machiningcapabilitybycategory -> machiningcapability,"
			+ "\n  machiningcapabilitybycategory_ServiceCategoryID: machiningcapabilitybycategory -> servicesandconsultantscategory,"
			+ "\n  materialbyservicecategory_MaterialID: materialbyservicecategory -> material_B,"
			+ "\n  materialbyservicecategory_ServiceCateogryID: materialbyservicecategory -> servicesandconsultantscategory,"
			+ "\n  moldmakingservicedetails_ServiceDetailsID: moldmakingservicedetails -> servicedetails,"
			+ "\n  moldmakingservicedetailsindustryserved_IndustryID: moldmakingservicedetailsindustryserved -> industry,"
			+ "\n  moldmakingservicedetailsindustryserved_MoldMakingServiceDetailID: moldmakingservicedetailsindustryserved -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingCapabilityID: moldmakingservicedetailsmoldorprocesstype -> moldorprocesstype,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingServiceDetailsID: moldmakingservicedetailsmoldorprocesstype -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsservices_MoldMakingServiceDetailsID: moldmakingservicedetailsservices -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsservices_ServiceID: moldmakingservicedetailsservices -> service,"
			+ "\n  servicebycategory_ServiceCategoryID: servicebycategory -> servicesandconsultantscategory,"
			+ "\n  servicebycategory_ServiceID: servicebycategory -> service,"
			+ "\n  servicedetails_Category: servicedetails -> servicesandconsultantscategory,"
			+ "\n  servicesandconsultantscategory_ParentID: servicesandconsultantscategory -> servicesandconsultantscategory,"
			+ "\n  supplierservicedetails_ServiceDetailsID: supplierservicedetails -> servicedetails,"
			+ "\n  supplierservicedetails_SupplierID: supplierservicedetails -> supplier,  "
			+ "\n//  "
			+ "\n edmcapability_to_capability : edmcapability -> capability,"
			+ "\n machiningcapability_to_capability : machiningcapability -> capability,"
			+ "\n process_to_moldorprocesstype : process -> moldorprocesstype,"
			+ "\n moldtypes_to_moldorprocesstype : moldtypes -> moldorprocesstype,"
			+ "\n// "
			+ "\n capability_service_capability : capability_service -> capability,"
			+ "\n capability_service_service : capability_service -> service,"
			+ "\n material_material_A : material_material -> material_A,"
			+ "\n material_material_B : material_material -> material_B;"
			+ "\n equations"
			+ "\n  servicesandconsultantscategory.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID = servicesandconsultantscategory.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID.servicesandconsultantscategory_ParentID,"
			+ "\n//  productorservicecategory.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id = productorservicecategory.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id.productorservicecategory_Parent_id,"
			+ "\n  capability.capability_Parent_id.capability_Parent_id.capability_Parent_id = capability.capability_Parent_id.capability_Parent_id.capability_Parent_id.capability_Parent_id;"
			+ "\n"
			+ "\n}"
			+ "\n"
			+ "\nmapping AC = {"
			+ "\n nodes"
			+ "\n  capability -> capability,"
			+ "\n  capabilitycategories-> capabilitycategories,"
			+ "\n  capabilityequipment->capabilityequipment ,"
			+ "\n  capabilityindustry-> capabilityindustry,"
			+ "\n  capabilitymaterials-> capabilitymaterials,"
			+ "\n  capabilityprocesses->capabilityprocesses ,"
			+ "\n  capabilitytypesofmolds->capabilitytypesofmolds ,"
			+ "\n  equipmenttype->equipmenttype ,"
			+ "\n  industry->industry ,"
			+ "\n  material->material_A,"
			+ "\n  moldtypes->moldtypes ,"
			+ "\n  process-> process,"
			+ "\n  productorservicecategory->servicesandconsultantscategory ,"
			+ "\n  supplier->supplier ,"
			+ "\n  suppliercapabilities->suppliercapabilities ,"
			+ "\n  unitcode-> unitcode;"
			+ "\n attributes"
			+ "\n  capability_Capability_Name ->capability_Capability_Name,"
			+ "\n  capability_Max_Length -> capability_Max_Length,"
			+ "\n  capability_Production_Volume_Max -> capability_Production_Volume_Max,"
			+ "\n  capability_Production_Volume_Min -> capability_Production_Volume_Min,"
			+ "\n  capability_Tolerance  -> capability_Tolerance,"
			+ "\n  equipmenttype_EquipmentType_Name -> equipmenttype_EquipmentType_Name,"
			+ "\n  industry_Industry_Name -> industry_Industry_Name,"
			+ "\n  material_Material_Name -> material_Material_Name,"
			+ "\n  moldtypes_MoldTypes_Name -> moldtypes_MoldTypes_Name,"
			+ "\n  process_Process_Name -> process_Process_Name,"
			+ "\n  productorservicecategory_Category_Name -> productorservicecategory_Category_Name,"
			+ "\n  productorservicecategory_isLeaf -> productorservicecategory_isLeaf,"
			+ "\n  supplier_Note -> supplier_Note,"
			+ "\n  supplier_Source -> supplier_Source,"
			+ "\n  unitcode_Code -> unitcode_Code,"
			+ "\n  unitcode_Description -> unitcode_Description;"
			+ "\n arrows"
			+ "\n  capability_Max_Length_Unit -> capability.capability_Max_Length_Unit,"
			+ "\n  capability_Parent_id -> capability.capability_Parent_id,"
			+ "\n  capability_Production_Volume_Max_Unit -> capability.capability_Production_Volume_Max_Unit,"
			+ "\n  capability_Production_Volume_Min_Unit -> capability.capability_Production_Volume_Min_Unit,"
			+ "\n  capability_Tolerance_Unit -> capability.capability_Tolerance_Unit,"
			+ "\n  capabilitycategories_Capability_id -> capabilitycategories.capabilitycategories_Capability_id,"
			+ "\n  capabilitycategories_ProductOrServiceCategory_id -> capabilitycategories.capabilitycategories_ProductOrServiceCategory_id,"
			+ "\n  capabilityequipment_Capability_id -> capabilityequipment.capabilityequipment_Capability_id,"
			+ "\n  capabilityequipment_EquipmentType_id -> capabilityequipment.capabilityequipment_EquipmentType_id,"
			+ "\n  capabilityindustry_Capability_id -> capabilityindustry.capabilityindustry_Capability_id,"
			+ "\n  capabilityindustry_Industry_id -> capabilityindustry.capabilityindustry_Industry_id,"
			+ "\n  capabilitymaterials_Capability_id -> capabilitymaterials.capabilitymaterials_Capability_id,"
			+ "\n  capabilitymaterials_Material_id -> capabilitymaterials.capabilitymaterials_Material_id,"
			+ "\n  capabilityprocesses_Capability_id -> capabilityprocesses.capabilityprocesses_Capability_id,"
			+ "\n  capabilityprocesses_Process_id -> capabilityprocesses.capabilityprocesses_Process_id,"
			+ "\n  capabilitytypesofmolds_Capability_id -> capabilitytypesofmolds.capabilitytypesofmolds_Capability_id, "
			+ "\n  capabilitytypesofmolds_MoldTypes_id -> capabilitytypesofmolds.capabilitytypesofmolds_MoldTypes_id,"
			+ "\n  productorservicecategory_Parent_id -> servicesandconsultantscategory.servicesandconsultantscategory_ParentID, "
			+ "\n  suppliercapabilities_Capability_id -> suppliercapabilities.suppliercapabilities_Capability_id, "
			+ "\n  suppliercapabilities_Supplier_id -> suppliercapabilities.suppliercapabilities_Supplier_id;"
			+ "\n} : A -> C"
			+ "\n"
			+ "\nmapping BC = {"
			+ "\n nodes"
			+ "\n  edmcapability -> edmcapability,"
			+ "\n  edmmachiningservicedetails -> edmmachiningservicedetails,"
			+ "\n  edmmachiningservicedetailscapabilities -> edmmachiningservicedetailscapabilities,"
			+ "\n  edmmachiningservicedetailsmaterials -> edmmachiningservicedetailsmaterials,"
			+ "\n  edmmachiningservicedetailspartlengths -> edmmachiningservicedetailspartlengths,"
			+ "\n  edmmachiningservicedetailsservices -> edmmachiningservicedetailsservices,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings -> edmmachiningservicedetailsspecialtymachinings,"
			+ "\n  industry -> industry,"
			+ "\n  machineshopservicedetails -> machineshopservicedetails,"
			+ "\n  machineshopservicedetailscapability -> machineshopservicedetailscapability,"
			+ "\n  machineshopservicedetailsmaterials -> machineshopservicedetailsmaterials,"
			+ "\n  machineshopservicedetailsservices -> machineshopservicedetailsservices,"
			+ "\n  machiningcapability -> machiningcapability,"
			+ "\n  machiningcapabilitybycategory -> machiningcapabilitybycategory,"
			+ "\n  material -> material_B,"
			+ "\n  materialbyservicecategory -> materialbyservicecategory,"
			+ "\n  moldmakingservicedetails -> moldmakingservicedetails,"
			+ "\n  moldmakingservicedetailsindustryserved -> moldmakingservicedetailsindustryserved,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype -> moldmakingservicedetailsmoldorprocesstype,"
			+ "\n  moldmakingservicedetailsservices -> moldmakingservicedetailsservices,"
			+ "\n  moldorprocesstype -> moldorprocesstype,"
			+ "\n  partlengthvaluelist -> partlengthvaluelist,"
			+ "\n  service -> service,"
			+ "\n  servicebycategory -> servicebycategory,"
			+ "\n  servicedetails -> servicedetails,"
			+ "\n  servicesandconsultantscategory -> servicesandconsultantscategory,"
			+ "\n  supplier -> supplier,"
			+ "\n  supplierservicedetails -> supplierservicedetails;"
			+ "\n attributes"
			+ "\n  edmcapability_EDMCapabilitiesName -> edmcapability_EDMCapabilitiesName,"
			+ "\n  edmmachiningservicedetails_DoMicroMachining -> edmmachiningservicedetails_DoMicroMachining,"
			+ "\n  industry_IndustryName -> industry_IndustryName,"
			+ "\n  machineshopservicedetailscapability_isSpecialty -> machineshopservicedetailscapability_isSpecialty,"
			+ "\n  machiningcapability_MachiningCapabilityName -> machiningcapability_MachiningCapabilityName,"
			+ "\n  machiningcapabilitybycategory_isSpecialty -> machiningcapabilitybycategory_isSpecialty,"
			+ "\n  material_MaterialName -> material_MaterialName,"
			+ "\n  moldorprocesstype_MoldOrProcessTypeName -> moldorprocesstype_MoldOrProcessTypeName,"
			+ "\n  partlengthvaluelist_LengthValue -> partlengthvaluelist_LengthValue,"
			+ "\n  service_ServiceName -> service_ServiceName,"
			+ "\n  servicedetails_ServiceDetailsName -> servicedetails_ServiceDetailsName,"
			+ "\n  servicesandconsultantscategory_CateoryName -> servicesandconsultantscategory_CateoryName,"
			+ "\n  servicesandconsultantscategory_isLeaf -> servicesandconsultantscategory_isLeaf,"
			+ "\n  supplier_CompanyInfo -> supplier_CompanyInfo,"
			+ "\n  supplier_Source -> supplier_Source;"
			+ "\n arrows"
			+ "\n  edmmachiningservicedetails_ServiceDetailsID -> edmmachiningservicedetails.edmmachiningservicedetails_ServiceDetailsID,"
			+ "\n  edmmachiningservicedetailscapabilities_EDMCapabilityID -> edmmachiningservicedetailscapabilities.edmmachiningservicedetailscapabilities_EDMCapabilityID,"
			+ "\n  edmmachiningservicedetailscapabilities_EDMMachiningServiceDetailsID -> edmmachiningservicedetailscapabilities.edmmachiningservicedetailscapabilities_EDMMachiningServiceDetailsID,"
			+ "\n  edmmachiningservicedetailsmaterials_EDMMachiningServiceDetailsID -> edmmachiningservicedetailsmaterials.edmmachiningservicedetailsmaterials_EDMMachiningServiceDetailsID,"
			+ "\n  edmmachiningservicedetailsmaterials_MaterialID -> edmmachiningservicedetailsmaterials.edmmachiningservicedetailsmaterials_MaterialID,"
			+ "\n  edmmachiningservicedetailspartlengths_EDMMachiningServiceDetailsID -> edmmachiningservicedetailspartlengths.edmmachiningservicedetailspartlengths_EDMMachiningServiceDetailsID,"
			+ "\n  edmmachiningservicedetailspartlengths_PartLengthValueListID -> edmmachiningservicedetailspartlengths.edmmachiningservicedetailspartlengths_PartLengthValueListID,"
			+ "\n  edmmachiningservicedetailsservices_EDMMachiningServiceDetailsID -> edmmachiningservicedetailsservices.edmmachiningservicedetailsservices_EDMMachiningServiceDetailsID,"
			+ "\n  edmmachiningservicedetailsservices_ServiceID -> edmmachiningservicedetailsservices.edmmachiningservicedetailsservices_ServiceID,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings_EDMMachiningServiceDetailsID -> edmmachiningservicedetailsspecialtymachinings.edmmachiningservicedetailsspecialtymachinings_EDMMachiningServiceDetailsID,"
			+ "\n  edmmachiningservicedetailsspecialtymachinings_MachiningCapabilityID -> edmmachiningservicedetailsspecialtymachinings.edmmachiningservicedetailsspecialtymachinings_MachiningCapabilityID,"
			+ "\n  machineshopservicedetails_ServiceDetailsID -> machineshopservicedetails.machineshopservicedetails_ServiceDetailsID,"
			+ "\n  machineshopservicedetailscapability_MachineShopServiceDetailsID -> machineshopservicedetailscapability.machineshopservicedetailscapability_MachineShopServiceDetailsID,"
			+ "\n  machineshopservicedetailscapability_MachiningCapabilityID -> machineshopservicedetailscapability.machineshopservicedetailscapability_MachiningCapabilityID,"
			+ "\n  machineshopservicedetailsmaterials_MachineShopServiceDetailsID -> machineshopservicedetailsmaterials.machineshopservicedetailsmaterials_MachineShopServiceDetailsID,"
			+ "\n  machineshopservicedetailsmaterials_MaterialID -> machineshopservicedetailsmaterials.machineshopservicedetailsmaterials_MaterialID,"
			+ "\n  machineshopservicedetailsservices_MachineShopServiceDetailsID -> machineshopservicedetailsservices.machineshopservicedetailsservices_MachineShopServiceDetailsID,"
			+ "\n  machineshopservicedetailsservices_ServiceID -> machineshopservicedetailsservices.machineshopservicedetailsservices_ServiceID,"
			+ "\n  machiningcapabilitybycategory_MachiningCapabilityID -> machiningcapabilitybycategory.machiningcapabilitybycategory_MachiningCapabilityID,"
			+ "\n  machiningcapabilitybycategory_ServiceCategoryID -> machiningcapabilitybycategory.machiningcapabilitybycategory_ServiceCategoryID,"
			+ "\n  materialbyservicecategory_MaterialID -> materialbyservicecategory.materialbyservicecategory_MaterialID,"
			+ "\n  materialbyservicecategory_ServiceCateogryID -> materialbyservicecategory.materialbyservicecategory_ServiceCateogryID,"
			+ "\n  moldmakingservicedetails_ServiceDetailsID -> moldmakingservicedetails.moldmakingservicedetails_ServiceDetailsID,"
			+ "\n  moldmakingservicedetailsindustryserved_IndustryID -> moldmakingservicedetailsindustryserved.moldmakingservicedetailsindustryserved_IndustryID,"
			+ "\n  moldmakingservicedetailsindustryserved_MoldMakingServiceDetailID -> moldmakingservicedetailsindustryserved.moldmakingservicedetailsindustryserved_MoldMakingServiceDetailID,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingCapabilityID -> moldmakingservicedetailsmoldorprocesstype.moldmakingservicedetailsmoldorprocesstype_MoldMakingCapabilityID,"
			+ "\n  moldmakingservicedetailsmoldorprocesstype_MoldMakingServiceDetailsID -> moldmakingservicedetailsmoldorprocesstype.moldmakingservicedetailsmoldorprocesstype_MoldMakingServiceDetailsID,"
			+ "\n  moldmakingservicedetailsservices_MoldMakingServiceDetailsID -> moldmakingservicedetailsservices.moldmakingservicedetailsservices_MoldMakingServiceDetailsID,"
			+ "\n  moldmakingservicedetailsservices_ServiceID -> moldmakingservicedetailsservices.moldmakingservicedetailsservices_ServiceID,"
			+ "\n  servicebycategory_ServiceCategoryID -> servicebycategory.servicebycategory_ServiceCategoryID,"
			+ "\n  servicebycategory_ServiceID -> servicebycategory.servicebycategory_ServiceID,"
			+ "\n  servicedetails_Category -> servicedetails.servicedetails_Category,"
			+ "\n  servicesandconsultantscategory_ParentID -> servicesandconsultantscategory.servicesandconsultantscategory_ParentID,"
			+ "\n  supplierservicedetails_ServiceDetailsID -> supplierservicedetails.supplierservicedetails_ServiceDetailsID,"
			+ "\n  supplierservicedetails_SupplierID -> supplierservicedetails.supplierservicedetails_SupplierID;"
			+ "\n} : B -> C"
			+ "\n"
			+ "\ninstance AC_Inst = SIGMA AC A_inst"
			+ "\ninstance BC_Inst = SIGMA BC B_inst"
			+ "\ninstance C_Inst = (AC_Inst + BC_Inst)"
			+ "\n"
	+"\nschema Hierarchy = {"
	+ "\n	nodes Material;"
	+ "\n	attributes ASWRITTEN;"
	+ "\n	arrows isa : Material -> Material;"
	+ "\n	equations Material.isa.isa.isa.isa.isa.isa.isa = Material.isa.isa.isa.isa.isa.isa;"
	+ "\n}"
	+ "\n"
	+ "\ninstance Material = {"
	+ "\n	nodes Material -> {"
	+ "\n		Material, "
	+ "\n		Ceramic, "
	+ "\n		Composite, "
	+ "\n		Metal, "
	+ "\n		Polymer, "
	+ "\n		Crystalline, "
	+ "\n		NonCrystalline, "
	+ "\n		Glass, "
	+ "\n		GlassCeramics, "
	+ "\n		Ferrous, "
	+ "\n		CastIron, "
	+ "\n		DieSteel, "
	+ "\n		Steel, "
	+ "\n		ToolSteel, "
	+ "\n		AlloySteel, "
	+ "\n		StainlessSteel, "
	+ "\n		NonFerrous, "
	+ "\n		SuperAlloy, "
	+ "\n		Stellite, "
	+ "\n		Iconel, "
	+ "\n		Hastelloy, "
	+ "\n		Elastomer, "
	+ "\n		Plastic, "
	+ "\n		Hermoset, "
	+ "\n		ThermoPlastic, "
	+ "\n		Nylon, "
	+ "\n		PVC, "
	+ "\n		Polyester};"
	+ "\n	attributes ASWRITTEN;"
	+ "\n	arrows isa -> {"
	+ "\n	(GlassCeramics,NonCrystalline),"
	+ "\n	(Glass,NonCrystalline),"
	+ "\n	(Crystalline,Ceramic),"
	+ "\n	(NonCrystalline,Ceramic),"
	+ "\n	(Ceramic,Material),"
	+ "\n	(Composite,Material),"
	+ "\n	(Metal,Material),"
	+ "\n	(Ferrous,Metal),"
	+ "\n	(NonFerrous,Metal),"
	+ "\n	(SuperAlloy,Metal),"
	+ "\n	(CastIron,Ferrous),"
	+ "\n	(DieSteel,Ferrous),"
	+ "\n	(Steel,Ferrous),"
	+ "\n	(ToolSteel,Ferrous),"
	+ "\n	(AlloySteel,Steel),"
	+ "\n	(StainlessSteel,AlloySteel),"
	+ "\n	(NonFerrous,Metal),"
	+ "\n	(SuperAlloy,Metal),"
	+ "\n	(Stellite,SuperAlloy),"
	+ "\n	(Iconel,SuperAlloy),"
	+ "\n	(Hastelloy,SuperAlloy),"
	+ "\n	(Elastomer,Polymer),"
	+ "\n	(Plastic,Polymer),"
	+ "\n	(Polymer,Material),"
	+ "\n	(Hermoset,Plastic),"
	+ "\n	(ThermoPlastic,Plastic),"
	+ "\n	(Nylon,ThermoPlastic),"
	+ "\n	(PVC,ThermoPlastic),"
	+ "\n	(Polyester,ThermoPlastic),"
	+ "\n	(Material,Material)};"
	+ "\n} : Hierarchy"
	+ "\n";







}
