/* The following code was generated by JFlex 1.4.3 on 11/18/13 4:54 PM */

/*
 * Generated on 11/18/13 4:54 PM
 */
package fql.parse;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * 
 */

public class FqlTokenMaker extends AbstractJFlexCTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int EOL_COMMENT = 4;
  public static final int YYINITIAL = 0;
  public static final int MLC = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\7\1\0\1\17\1\15\22\0\1\17\1\24\1\14"+
    "\1\16\1\1\1\24\1\24\1\6\1\25\1\25\1\21\1\66\1\24"+
    "\1\67\1\23\1\20\1\4\3\4\4\4\2\3\1\36\1\24\1\15"+
    "\1\66\1\70\1\24\1\16\1\50\3\5\1\56\1\5\1\60\1\1"+
    "\1\54\3\1\1\61\1\57\3\1\1\53\1\51\1\55\2\1\1\52"+
    "\3\1\1\25\1\10\1\25\1\71\1\2\1\0\1\42\1\13\1\43"+
    "\1\62\1\35\1\32\1\44\1\26\1\33\2\1\1\34\1\41\1\40"+
    "\1\47\1\30\1\45\1\12\1\31\1\27\1\11\1\63\1\37\1\64"+
    "\1\46\1\65\1\22\1\71\1\22\1\24\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\2\1\1\2\1\3\2\1\1\4\1\5\1\1"+
    "\1\6\1\7\20\1\1\10\1\11\5\10\1\12\3\10"+
    "\1\0\1\13\2\1\2\4\1\14\1\15\1\16\3\1"+
    "\1\17\25\1\1\20\11\0\1\1\1\4\1\21\1\4"+
    "\6\1\1\22\17\1\11\0\1\1\1\4\5\1\1\23"+
    "\12\1\2\0\1\24\2\0\1\25\1\0\1\1\1\4"+
    "\11\1\5\0\1\1\1\4\22\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\256\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0244\0\256\0\256\0\u027e\0\u02b8"+
    "\0\u02f2\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488"+
    "\0\u04c2\0\u04fc\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\256"+
    "\0\u0658\0\u0692\0\u06cc\0\u0706\0\u0740\0\256\0\u077a\0\u07b4"+
    "\0\u07ee\0\u0828\0\u0862\0\u089c\0\u08d6\0\u0910\0\u094a\0\256"+
    "\0\256\0\256\0\u0984\0\u09be\0\u09f8\0\350\0\u0a32\0\u0a6c"+
    "\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54\0\u0b8e\0\u0bc8\0\u0c02\0\u0c3c"+
    "\0\u0c76\0\u0cb0\0\u0cea\0\u0d24\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c"+
    "\0\u0e46\0\u0e80\0\u0eba\0\256\0\u0ef4\0\u0f2e\0\u0f68\0\u0fa2"+
    "\0\u0fdc\0\u1016\0\u1050\0\u108a\0\u10c4\0\u10fe\0\u1138\0\256"+
    "\0\u1172\0\u11ac\0\u11e6\0\u1220\0\u125a\0\u1294\0\u12ce\0\350"+
    "\0\u1308\0\u1342\0\u137c\0\u13b6\0\u13f0\0\u142a\0\u1464\0\u149e"+
    "\0\u14d8\0\u1512\0\u154c\0\u1586\0\u15c0\0\u15fa\0\u1634\0\u166e"+
    "\0\u16a8\0\u16e2\0\u171c\0\u1756\0\u1790\0\u17ca\0\u1804\0\u183e"+
    "\0\u1878\0\u18b2\0\u18ec\0\u1926\0\u1960\0\u199a\0\u19d4\0\350"+
    "\0\u1a0e\0\u1a48\0\u1a82\0\u1abc\0\u1af6\0\u1b30\0\u1b6a\0\u1ba4"+
    "\0\u1bde\0\u1c18\0\u1c52\0\u1c8c\0\u1cc6\0\u1d00\0\u1d3a\0\u1d74"+
    "\0\u1dae\0\u1de8\0\u1e22\0\u1e5c\0\u1e96\0\u1ed0\0\u1f0a\0\u1f44"+
    "\0\u1f7e\0\u1fb8\0\u1ff2\0\u202c\0\u2066\0\u1cc6\0\u20a0\0\u1d74"+
    "\0\u20da\0\u2114\0\u214e\0\u2188\0\u21c2\0\u21fc\0\u2236\0\u2270"+
    "\0\u22aa\0\u22e4\0\u231e\0\u2358\0\u2392\0\u23cc\0\u2406\0\u2440"+
    "\0\u247a\0\u24b4\0\u24ee\0\u2528\0\u2562";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\2\6\1\5\1\4\1\7\1\4\1\10"+
    "\1\11\1\5\1\12\2\4\1\13\1\14\1\15\1\16"+
    "\2\4\1\16\1\5\1\17\1\20\1\21\1\22\1\23"+
    "\1\5\1\24\1\15\1\5\1\25\1\26\1\27\1\30"+
    "\1\5\1\31\2\5\1\32\1\33\10\5\1\34\1\35"+
    "\2\5\1\15\1\36\1\4\1\15\7\37\1\40\11\37"+
    "\1\41\4\37\1\42\3\37\1\43\4\37\1\44\32\37"+
    "\7\45\1\46\16\45\1\47\3\45\1\50\4\45\1\51"+
    "\32\45\73\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\27\5\4\0\3\53\2\6\1\53\2\0\4\53"+
    "\2\0\1\53\7\0\10\53\1\0\27\53\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\1\5\1\54"+
    "\25\5\5\0\5\5\2\0\1\52\3\5\12\0\7\5"+
    "\1\55\1\0\27\5\4\0\7\12\1\56\1\57\3\12"+
    "\1\60\55\12\17\0\1\13\72\0\1\61\1\62\51\0"+
    "\5\5\2\0\1\52\1\5\1\63\1\5\12\0\1\64"+
    "\7\5\1\0\27\5\5\0\5\5\2\0\1\52\1\5"+
    "\1\65\1\5\12\0\5\5\1\66\2\5\1\0\27\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\1\5\1\67"+
    "\3\5\1\70\2\5\1\0\1\5\1\71\2\5\1\72"+
    "\22\5\5\0\5\5\2\0\1\52\3\5\12\0\3\5"+
    "\1\73\4\5\1\0\27\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\1\5\1\74\21\5\1\66"+
    "\3\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\1\5\1\75\4\5\1\76\15\5\1\77\1\100"+
    "\1\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\10\5\1\101\16\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\3\5\1\102\23\5\5\0"+
    "\5\5\2\0\1\52\1\5\1\103\1\5\12\0\1\5"+
    "\1\104\1\105\5\5\1\0\27\5\5\0\5\5\2\0"+
    "\1\52\1\106\2\5\12\0\10\5\1\0\27\5\5\0"+
    "\5\5\2\0\1\52\1\107\2\5\12\0\10\5\1\0"+
    "\27\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\12\5\1\110\14\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\15\5\1\111\11\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\7\5\1\112\1\0"+
    "\27\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\10\5\1\113\16\5\74\0\1\15\1\0\7\37"+
    "\1\0\11\37\1\0\4\37\1\0\3\37\1\0\4\37"+
    "\1\0\32\37\20\0\1\114\100\0\1\115\71\0\1\116"+
    "\3\0\1\117\75\0\1\120\32\0\7\45\1\0\16\45"+
    "\1\0\3\45\1\0\4\45\1\0\32\45\27\0\1\121"+
    "\71\0\1\122\3\0\1\123\75\0\1\124\43\0\1\125"+
    "\60\0\6\53\2\0\4\53\2\0\1\53\7\0\10\53"+
    "\1\0\27\53\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\5\5\1\73\2\5\1\0\27\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\6\5\1\126\1\5\1\0\27\5"+
    "\4\0\10\56\1\127\3\56\1\130\61\56\1\12\1\56"+
    "\1\12\1\0\1\12\1\131\3\12\12\56\1\12\2\56"+
    "\1\12\5\56\1\12\31\56\1\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\3\5\1\132\23\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\7\5\1\133\1\0"+
    "\27\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\10\5\1\134\16\5\5\0\5\5\2\0\1\52"+
    "\1\5\1\135\1\5\12\0\10\5\1\0\27\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\10\5\1\0\5\5"+
    "\1\136\21\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\10\5\1\0\23\5\1\66\3\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\1\137\7\5\1\0\27\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\1\5\1\66\6\5"+
    "\1\0\27\5\5\0\5\5\2\0\1\52\1\5\1\66"+
    "\1\5\12\0\1\5\1\140\1\5\1\141\2\5\1\66"+
    "\1\5\1\0\27\5\5\0\5\5\2\0\1\52\1\142"+
    "\2\5\12\0\10\5\1\0\27\5\5\0\5\5\2\0"+
    "\1\52\1\143\2\5\12\0\10\5\1\0\27\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\10\5\1\0\3\5"+
    "\1\144\23\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\1\5\1\145\6\5\1\0\27\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\10\5\1\0\23\5\1\146\3\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\2\5\1\147"+
    "\5\5\1\0\27\5\5\0\5\5\2\0\1\52\1\5"+
    "\1\150\1\5\12\0\10\5\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\1\5\1\151\6\5\1\0"+
    "\27\5\5\0\5\5\2\0\1\52\3\5\12\0\2\5"+
    "\1\152\5\5\1\0\27\5\5\0\5\5\2\0\1\52"+
    "\1\5\1\153\1\5\12\0\10\5\1\0\27\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\7\5\1\154\1\0"+
    "\27\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\13\5\1\155\13\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\21\5\1\156\5\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\6\5\1\157\1\5"+
    "\1\0\27\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\5\5\1\71\2\5\1\0\27\5\33\0\1\160\72\0"+
    "\1\161\75\0\1\162\74\0\1\163\61\0\1\164\72\0"+
    "\1\165\75\0\1\166\74\0\1\167\35\0\3\170\5\0"+
    "\1\170\16\0\1\170\2\0\1\170\4\0\2\170\4\0"+
    "\1\170\5\0\1\170\3\0\1\170\10\0\5\5\2\0"+
    "\1\52\3\5\12\0\10\5\1\0\3\5\1\171\23\5"+
    "\4\0\7\56\1\0\65\56\3\172\2\56\1\127\2\56"+
    "\1\172\1\130\15\56\1\172\2\56\1\172\4\56\2\172"+
    "\4\56\1\172\5\56\1\172\3\56\1\172\7\56\1\0"+
    "\5\5\2\0\1\52\3\5\12\0\10\5\1\0\1\5"+
    "\1\173\25\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\10\5\1\0\1\5\1\66\25\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\2\5\1\66\5\5\1\0\27\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\5\5\1\174"+
    "\2\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\2\5\1\175\24\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\7\5\1\176\1\0\27\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\1\5\1\177"+
    "\6\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\2\5\1\200\24\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\3\5\1\201"+
    "\23\5\5\0\5\5\2\0\1\52\3\5\12\0\6\5"+
    "\1\66\1\5\1\0\27\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\7\5\1\202\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\7\5\1\203\1\0\27\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\2\5\1\204"+
    "\5\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\10\5\1\205\16\5\5\0\5\5"+
    "\2\0\1\52\1\5\1\206\1\5\12\0\10\5\1\0"+
    "\27\5\5\0\5\5\2\0\1\52\3\5\12\0\6\5"+
    "\1\207\1\5\1\0\27\5\5\0\5\5\2\0\1\52"+
    "\1\5\1\207\1\5\12\0\10\5\1\0\27\5\5\0"+
    "\5\5\2\0\1\52\1\5\1\210\1\5\12\0\10\5"+
    "\1\0\27\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\10\5\1\0\14\5\1\211\12\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\10\5\1\0\22\5\1\212\4\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\1\5\1\175"+
    "\6\5\1\0\27\5\34\0\1\213\77\0\1\214\70\0"+
    "\1\161\57\0\1\215\76\0\1\216\77\0\1\217\70\0"+
    "\1\165\57\0\1\220\51\0\3\221\5\0\1\221\16\0"+
    "\1\221\2\0\1\221\4\0\2\221\4\0\1\221\5\0"+
    "\1\221\3\0\1\221\10\0\5\5\2\0\1\52\3\5"+
    "\12\0\1\5\1\222\6\5\1\0\27\5\4\0\3\56"+
    "\3\223\2\56\1\127\2\56\1\223\1\130\15\56\1\223"+
    "\2\56\1\223\4\56\2\223\4\56\1\223\5\56\1\223"+
    "\3\56\1\223\7\56\1\0\5\5\2\0\1\52\3\5"+
    "\12\0\3\5\1\224\4\5\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\1\5\1\225"+
    "\25\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\3\5\1\66\23\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\2\5\1\226\24\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\10\5\1\0\3\5"+
    "\1\227\23\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\1\5\1\230\6\5\1\0\27\5\5\0\5\5\2\0"+
    "\1\52\1\5\1\231\1\5\12\0\10\5\1\0\27\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\3\5\1\66"+
    "\4\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\5\5\1\232\2\5\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\1\203\26\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\5\5\1\233"+
    "\2\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\7\5\1\66\17\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\7\5\1\200"+
    "\17\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\15\5\1\234\11\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\11\5\1\66\15\5\35\0"+
    "\1\161\4\0\1\214\53\0\1\235\52\0\1\215\1\236"+
    "\3\215\1\236\2\0\3\215\2\0\1\236\1\0\1\215"+
    "\1\236\1\0\3\236\10\215\1\236\27\215\2\236\33\0"+
    "\1\165\4\0\1\217\53\0\1\237\52\0\1\220\1\240"+
    "\3\220\1\240\2\0\3\220\2\0\1\240\1\0\1\220"+
    "\1\240\1\0\3\240\10\220\1\240\27\220\2\240\5\0"+
    "\3\241\5\0\1\241\16\0\1\241\2\0\1\241\4\0"+
    "\2\241\4\0\1\241\5\0\1\241\3\0\1\241\10\0"+
    "\5\5\2\0\1\52\3\5\12\0\5\5\1\242\2\5"+
    "\1\0\27\5\4\0\3\56\3\243\2\56\1\127\2\56"+
    "\1\243\1\130\15\56\1\243\2\56\1\243\4\56\2\243"+
    "\4\56\1\243\5\56\1\243\3\56\1\243\7\56\1\0"+
    "\5\5\2\0\1\52\3\5\12\0\4\5\1\244\3\5"+
    "\1\0\27\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\10\5\1\0\5\5\1\140\21\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\10\5\1\0\3\5\1\200\23\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\10\5\1\0"+
    "\1\5\1\245\25\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\5\5\1\246\2\5\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\1\5\1\77"+
    "\25\5\5\0\5\5\2\0\1\52\3\5\12\0\10\5"+
    "\1\0\1\5\1\247\25\5\5\0\5\5\2\0\1\52"+
    "\2\5\1\250\12\0\10\5\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\16\5\1\251"+
    "\10\5\24\0\1\215\71\0\1\220\54\0\3\5\5\0"+
    "\1\5\16\0\1\5\2\0\1\5\4\0\2\5\4\0"+
    "\1\5\5\0\1\5\3\0\1\5\10\0\5\5\2\0"+
    "\1\52\3\5\12\0\10\5\1\0\10\5\1\252\16\5"+
    "\4\0\3\56\3\12\2\56\1\127\2\56\1\12\1\130"+
    "\15\56\1\12\2\56\1\12\4\56\2\12\4\56\1\12"+
    "\5\56\1\12\3\56\1\12\7\56\1\0\5\5\2\0"+
    "\1\52\3\5\12\0\10\5\1\0\10\5\1\253\16\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\10\5\1\0"+
    "\4\5\1\254\22\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\10\5\1\255\16\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\5\5\1\200"+
    "\21\5\5\0\5\5\2\0\1\52\1\256\2\5\12\0"+
    "\10\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\16\5\1\257\10\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\1\5\1\260"+
    "\25\5\5\0\5\5\2\0\1\52\1\5\1\142\1\5"+
    "\12\0\10\5\1\0\27\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\7\5\1\200\1\0\27\5\5\0\5\5"+
    "\2\0\1\52\3\5\12\0\10\5\1\0\1\5\1\203"+
    "\25\5\5\0\5\5\2\0\1\52\3\5\12\0\1\5"+
    "\1\146\6\5\1\0\27\5\5\0\5\5\2\0\1\52"+
    "\3\5\12\0\10\5\1\0\17\5\1\261\7\5\5\0"+
    "\5\5\2\0\1\52\3\5\12\0\10\5\1\0\3\5"+
    "\1\262\23\5\5\0\5\5\2\0\1\52\3\5\12\0"+
    "\10\5\1\0\20\5\1\66\6\5\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\6\5\1\263\1\5\1\0\27\5"+
    "\5\0\5\5\2\0\1\52\3\5\12\0\5\5\1\264"+
    "\2\5\1\0\27\5\5\0\5\5\2\0\1\52\3\5"+
    "\12\0\10\5\1\0\26\5\1\265\5\0\5\5\2\0"+
    "\1\52\3\5\12\0\7\5\1\66\1\0\27\5\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9628];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\5\1\2\11\21\1\1\11"+
    "\5\1\1\11\3\1\1\0\5\1\3\11\31\1\1\11"+
    "\11\0\2\1\1\11\27\1\11\0\22\1\2\0\1\1"+
    "\2\0\1\1\1\0\13\1\5\0\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[181];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */


	/**
	 * Constructor.  This must be here because JFlex does not generate a
	 * no-parameter constructor.
	 */
	public FqlTokenMaker() {
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addToken(int, int, int)
	 */
	private void addHyperlinkToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, true);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 * @see #addHyperlinkToken(int, int, int)
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so, false);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *        occurs.
	 * @param hyperlink Whether this token is a hyperlink.
	 */
	public void addToken(char[] array, int start, int end, int tokenType,
						int startOffset, boolean hyperlink) {
		super.addToken(array, start,end, tokenType, startOffset, hyperlink);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { "//", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *        <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
						case Token.COMMENT_MULTILINE:
				state = MLC;
				start = text.offset;
				break;

			/* No documentation comments */
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new Token();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 */
	private boolean zzRefill() {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(Reader reader) {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FqlTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FqlTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { addNullToken(); return firstToken;
          }
        case 22: break;
        case 14: 
          { start = zzMarkedPos-2; yybegin(MLC);
          }
        case 23: break;
        case 5: 
          { addToken(Token.WHITESPACE);
          }
        case 24: break;
        case 17: 
          { addToken(Token.ERROR_STRING_DOUBLE);
          }
        case 25: break;
        case 19: 
          { addToken(Token.RESERVED_WORD);
          }
        case 26: break;
        case 7: 
          { addToken(Token.SEPARATOR);
          }
        case 27: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 28: break;
        case 10: 
          { addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 29: break;
        case 13: 
          { start = zzMarkedPos-2; yybegin(EOL_COMMENT);
          }
        case 30: break;
        case 4: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 31: break;
        case 18: 
          { addToken(Token.DATA_TYPE);
          }
        case 32: break;
        case 16: 
          { yybegin(YYINITIAL); addToken(start,zzStartRead+2-1, Token.COMMENT_MULTILINE);
          }
        case 33: break;
        case 12: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 34: break;
        case 21: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_EOL); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_EOL); start = zzMarkedPos;
          }
        case 35: break;
        case 20: 
          { int temp=zzStartRead; addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); addHyperlinkToken(temp,zzMarkedPos-1, Token.COMMENT_MULTILINE); start = zzMarkedPos;
          }
        case 36: break;
        case 15: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 37: break;
        case 11: 
          { addToken(Token.ERROR_NUMBER_FORMAT);
          }
        case 38: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 39: break;
        case 6: 
          { addToken(Token.OPERATOR);
          }
        case 40: break;
        case 8: 
          { 
          }
        case 41: break;
        case 9: 
          { addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
          }
        case 42: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case EOL_COMMENT: {
              addToken(start,zzStartRead-1, Token.COMMENT_EOL); addNullToken(); return firstToken;
            }
            case 182: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 183: break;
            case MLC: {
              addToken(start,zzStartRead-1, Token.COMMENT_MULTILINE); return firstToken;
            }
            case 184: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
